### ISSUE TITLE
Cannot_Generate_Plots_Using_PBstat.py

### ISSUE THREAD

**Issue by TJRnarwani** [pierrepo/PBxplore#100]
Hi
I tried generating stats from my PB.count file but the script PBstat.py breaks with an error:

"Traceback (most recent call last):
  File "PBstat.py", line 202, in <module>
    pbstat_cli()
  File "PBstat.py", line 170, in pbstat_cli
    pbx.analysis.plot_map(file_fig_name, count, residue_min, residue_max)
AttributeError: 'module' object has no attribute 'plot_map'"

Is there something which I would be missing? or it's a bug?

**Comment by jbarnoud** [comment]
`PBstat` should check for matplotlib.

**Comment by TJRnarwani** [comment]
@jbarnoud Thanks, it worked.. :100: 
:+1

**Comment by HubLot** [comment]
issue can be closed thanks to PR #107
