### ISSUE TITLE
Create package for Anaconda

### ISSUE THREAD

**Issue by jbarnoud** [pierrepo/PBxplore#102]
Anaconda is a python distribution for science and data analysis uses. It is growing in popularity as it allows to set up a scientific stack for python quite easily. We could have a package for that distribution. See <http://conda.pydata.org/docs/build_tutorials/pkgs.html>.

In #30, @alexdb27 suggested a package for Ethough Python Distribution (now Enthough Canopy). I did not find if it is possible to create a package for canopy, but the popularity of this distribution seems declining anyway.

**Comment by HubLot** [comment]
see #131
