### ISSUE TITLE
Travis failed when building the doc

### ISSUE THREAD

**Issue by HubLot** [pierrepo/PBxplore#111]
Travis cannot install pandoc for building the documentation. 
Here the log:

```
$ if [[ $SETUP == 'doc' ]]; then ./doc/source/install_pandoc.sh; fi
Config file path source is default config file.
Config file /home/travis/.cabal/config not found.
Writing default configuration to /home/travis/.cabal/config
Downloading the latest package list from hackage.haskell.org
Resolving dependencies...
cabal: Could not resolve dependencies:
next goal: pandoc (user goal)
rejecting: pandoc-1.16.0.2, 1.16.0.1, 1.16, 1.15.2.1, 1.15.2 (global
constraint requires ==1.15.1.1)
trying: pandoc-1.15.1.1
trying: pandoc-1.15.1.1:+https
trying: http-client-tls-0.2.2 (dependency of pandoc-1.15.1.1:+https)
trying: tls-1.3.4 (dependency of http-client-tls-0.2.2)
trying: transformers-0.5.1.0 (dependency of tls-1.3.4)
trying: yaml-0.8.15.3 (dependency of pandoc-1.15.1.1)
trying: enclosed-exceptions-1.0.1.1 (dependency of yaml-0.8.15.3)
trying: monad-control-1.0.0.5 (dependency of enclosed-exceptions-1.0.1.1)
trying: lifted-base-0.2.3.6 (dependency of enclosed-exceptions-1.0.1.1)
next goal: resourcet (dependency of yaml-0.8.15.3)
rejecting: resourcet-1.1.7.1, 1.1.7, 1.1.6, 1.1.5, 1.1.4.1, 1.1.4, 1.1.3.3,
1.1.3.2 (conflict: transformers==0.5.1.0, resourcet => transformers>=0.2.2 &&
<0.5)
rejecting: resourcet-1.1.3.1, 1.1.3, 1.1.2.3, 1.1.2.2, 1.1.2.1, 1.1.2, 1.1.1,
1.1.0.1, 1.1.0, 0.4.10.2, 0.4.10.1, 0.4.10, 0.4.9, 0.4.8, 0.4.7.2, 0.4.7.1,
0.4.7, 0.4.6, 0.4.5, 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.4.0.2 (conflict:
monad-control==1.0.0.5, resourcet => monad-control>=0.3.1 && <0.4)
rejecting: resourcet-0.4.0.1, 0.4.0, 0.3.3.1, 0.3.3, 0.3.2.2, 0.3.2.1, 0.3.2,
0.3.1, 0.3.0 (conflict: lifted-base==0.2.3.6, resourcet => lifted-base>=0.1 &&
<0.2)

The command "if [[ $SETUP == 'doc' ]]; then ./doc/source/install_pandoc.sh; fi" failed and exited with 1 during .

```

I think it's due again to cabal and that the default version of pandoc installed through it has changed again. (see the previous issue #109)
I'm on it

**Comment by jbarnoud** [comment]
With the update of Ubuntu on Travis (now ubuntu precise), the installed version of pandoc (or the version available with apt-get) should be recent enough. We may not need to use cabal any more.

**Comment by HubLot** [comment]
Nop, with precice, the pandoc version available is 1.9. The "--filter" option we used required pandoc >= 1.12.
We still stuck with cabal :(

**Comment by HubLot** [comment]
So, the issue is that cabal cannot solve the dependencies to install pandoc: either the last one 1.16 or the previous one we used 1.15.X
So far everything I tried failed:
  - Use the pandoc version from the repository: doesn't work due to a too old version (see my previous message).
  - add the `--max-backjumps=-1` to the cabal command line (`cabal install pandoc --max-backjumps=-1`) to search exhaustively through all packages to resolve dependencies: failed due to a timeout on Travis (it takes too much time).
  - Use the procedure on pandoc website, i.e update cabal through cabal (`cabal install cabal-install`) then install pandoc (`cabal install pandoc --max-backjumps=-1`): the update fails because some libraries cannot be installed...

I point out the 2 last options worked on my computer. Since they do, I'll try to retrieve the good versions of dependencies and installed them manually in `install_pandoc.sh`.

**Comment by jbarnoud** [comment]
I made it work! The trick is to install the right version of resourcet to help the resolution of the dependencies. See <https://github.com/jbarnoud/PBxplore/blob/fix-cabal/doc/source/install_pandoc.sh> and <https://travis-ci.org/jbarnoud/PBxplore/jobs/106213180>.

**Comment by HubLot** [comment]
youhou!

**Comment by jbarnoud** [comment]
For future reference, I saved the travis log in a gist <https://gist.github.com/jbarnoud/6a1436ff6f0e44c79bcb> in the mess of that log are the version of everything cabal installed.
