### ISSUE TITLE
Get rid of R

### ISSUE THREAD

**Issue by jbarnoud** [pierrepo/PBxplore#13]
PBxplore uses R to draw figures and to perform hierarchical clustering. This implies a heavy dependence to R;. It also requires to know two languages to maintain the software instead of one. Finally, as R is called via subprocess rather that via rpy, it requires to write intermediate scripts which is error prone and difficult to maintain.

All the thing done with R could be done in python.

Figures could be drawn using the matplotlib library. This would imply a dependence to the matplotlib python package, yet depending on a python package is lighter in a python environment than depending on an external interpreter. Also, the python scientific stack is already required through the numpy package.

Hierarchical clustering is available in the scipy module: <http://docs.scipy.org/doc/scipy/reference/cluster.hierarchy.html>.  As matplotlib, scipy os part of the classical python scientific stack. Other python modules implement hierarchical clustering (see <http://nbviewer.ipython.org/github/OxanaSachenkova/hclust-python/blob/master/hclust.ipynb> and <http://bioinformatics.org.au/tools/hclust/>) but they would create dependencies to less classical python modules.

R is called in two files: PBstat.py and PBclust.py.

**Comment by alexdb27** [comment]
One question is -i'm playing devil's advocate- that Scipy+Matplotlib also evolve. R seems quite stable, is it the same thing for both ?
We need a comparison on some simple examples...
PS: is it easy to use with Mac ?
PS2: is it not a big work ?

**Comment by jbarnoud** [comment]
On 22/04/15 10:20, Alexandre G. de Brevern wrote:
>
> One question is -i'm playing devil's advocate- that Scipy+Matplotlib 
> also evolve. R seems quite stable, is it the same thing for both ?
> We need a comparison on some simple examples...
> PS: is it easy to use with Mac ?
> PS2: is it not a big work ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pierrepo/PBxplore/issues/13#issuecomment-95070832>.
>
Scipy and Matplotlib are quite stable and well tested. They are as easy 
to install on mac as most python library as they can be installed using 
pip. Being very popular python packages, they can also be installed 
using package managers like macport or fink.

There are two main points at getting rid of R:

* whithout R, PBxplore will be easier to install. There will not be less 
dependency as they R will be replaced by other dependencies. Yet, these 
new dependencies can be installed with the same process as other 
packages we already depend on (like numpy). Ultimately, can we will be 
able to install PBxplore with a single command line.
* having 2 languages to handle make it more difficult to maintain.

Removing R is some work. But it is not an awful lot either. It may not 
be a priority but we will really benefit from it.

**Comment by pierrepo** [comment]
I agree with @jbarnoud.
Actually, R is not that stable. See for instance the issue we had recently regarding the name of the ward method to use in hclust (issue #31).
If a user is able to install numpy (major requirement for PBxplore) on his computer he will be able to install scipy and matplotlib as well.

**Comment by alexdb27** [comment]
- One point R is stable for most of the common functions. 
hclust was considered as good for more than 10 years (is it the case with Python libs such as biopython or similar, ... seems not). The Ward question is specific question.
- If scipy and matplotlib are simple to install for all, it is excellent.
- My main question is the quality of the clustering with various python libs. We need to have some tests to ensure it. I'm sure it will be.

**Comment by alexdb27** [comment]
So, where are we now ??

**Comment by pierrepo** [comment]
Regarding graphics, we are almost done. PBs distribution map is now in Python (see issue #52 ) and Neq vs sequence will soon be in Python too.
The last point is the clustering. Maybe we could implement just one clustering method in Python (hclust or k-means). Ping @jbarnoud ?

**Comment by jbarnoud** [comment]
The only remaining dependancy to R is the clustering that we will revamp anyway. I set this issue as a duplicate of #64 and close it.
