### ISSUE TITLE
Tests fail with he latest version of weblogo

### ISSUE THREAD

**Issue by jbarnoud** [pierrepo/PBxplore#133]
`weblogolib.ColorGroup` does not exist anymore.

**Comment by HubLot** [comment]
Indeed. It's now `weblogolib.SymbolColor`.
How can we manage that? Change it and precise the number of version supported ?

**Comment by jbarnoud** [comment]
Is it just the name that changes? Is the prototype the same? If so, we could just link them both to the same name.

**Comment by HubLot** [comment]
Prototype is the same yes. You can check my PR

**Comment by HubLot** [comment]
fix in #134
