### ISSUE TITLE
Remove Clustering

### ISSUE THREAD

**Issue by HubLot** [pierrepo/PBxplore#136]
In order to remove properly the clustering parts of PBxplore without losing the code, I offer this procedure :
- [x] Create 2 branches called _clust_R_ and _clust_python_ as clone of the current _master_
- [x] Remove all R clustering from master (already done here: https://github.com/HubLot/PBxplore/commit/d56759f010de2f693b9ef41f33de7e5bed026ffa)
- [x] Put @jbarnoud's work (#106) into _clust_python_ branch.

**Comment by jbarnoud** [comment]
For the record, I have a PR ongoing to remove clustering. I plan to 
submit it before the end of the month. In addition to the removal of the 
code, the PR removes the tests, the doc, and the examples.

Indeed, the current code should be kept in a separate branch.

**Comment by HubLot** [comment]
done in #143
