### ISSUE TITLE
PBxplore from PyPI (v1.0) does not seem to read *.pdb.gz anymore

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/PBxplore#138]
```
wget https://files.rcsb.org/download/3ICH.pdb.gz
PBassign -p 3ICH.pdb.gz -o toto
cat toto.PB.fasta
```

File `toto.PB.fasta` is empty.

**Comment by HubLot** [comment]
same issue with the master version

**Comment by HubLot** [comment]
Well, in fact, we didn't include `.pdb.gz` extension in the list of authorized extensions... See in https://github.com/pierrepo/PBxplore/blob/master/pbxplore/structure/PDB.py :

```python 
PDB_EXTENSIONS = ('.pdb', '.PDB', '.ent', '.ENT4')
PDBx_EXTENSIONS = ('.cif', '.CIF', '.cif.gz', '.CIF.GZ')
```
We dont neither have a test for this case (but we do for `cif.gz`). 
I'll do a PR to add the correct extensions and a test case ;)
