### ISSUE TITLE
PDBx/mmCIF support

### ISSUE THREAD

**Issue by jbarnoud** [pierrepo/PBxplore#14]
PBxplore does not read PBDx/mmCIF files. Yet, the PDB format is going to be deprecated soon (<http://pdbj.org/help/data-format>), and will be replaced by PBDx/mmCIF.

**Comment by pierrepo** [comment]
Hello @jbarnoud,

could you have a look to the new release of this branch? I have added new tests and .cif.gz files are handled correctly in regression tests.

* I made only one class for PDB and PDBx that is called from PBassign.py. I don't think we need two classes yet.
* I removed sys.exit from modules.

**Comment by pierrepo** [comment]
PDBx/mmCIF is now supported.
