### ISSUE TITLE
Check PEP8 compliance

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/PBxplore#145]
Check (and improve) PEP8 compliance with pylint or pyflake.

**Comment by pierrepo** [comment]
This could do the work: https://github.com/OrkoHunter/pep8speaks

**Comment by HubLot** [comment]
This looks great. We will need to tweak it a little bit but this could be useful.
I tested locally pycodestyle (https://github.com/PyCQA/pycodestyle) and there is not so much errors. 
See this gist: https://gist.github.com/HubLot/790581500542c4015ba4e892deea6123

**Comment by pierrepo** [comment]
OK. We could tweak it with a ``.pep8speaks.yml`` file. For instance, we could increase the max line length: 

    pycodestyle:
        max-line-length: 100  # Default is 79 in PEP8

**Comment by HubLot** [comment]
Yeah, plus we have some lines which are not PEP8 compliant but increase readability (for example, https://github.com/pierrepo/PBxplore/blob/master/pbxplore/assignment.py#L51 or https://github.com/pierrepo/PBxplore/blob/master/pbxplore/structure/structure.py#L305)

**Comment by pierrepo** [comment]
@HubLot can you give a try to pep8speaks?

**Comment by HubLot** [comment]
Here a working example : https://github.com/HubLot/PBxplore/pull/2#issuecomment-283948814 :smile:

**Comment by pierrepo** [comment]
Sounds good. Could we silent "E501 line too long" errors and fix other ones?
I believe we could use pep8speaks in production. What do you think?

**Comment by HubLot** [comment]
We could use it yes but we will still have some errors due to certain lines which don't follow PEP8 but increase the readibility of the code (see my previous examples)

**Comment by pierrepo** [comment]
OK. No need then. I close this issue.
