### ISSUE TITLE
PBstat does not generate weblogo anymore

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/PBxplore#152]
When the WebLogo Python lib is installed, `PBstat` generates empty ouput files with the `--logo` option.

This is the same of all image formats (pdf, jpg and png).

**Comment by pierrepo** [comment]
@HubLot could you have a look?

**Comment by HubLot** [comment]
I don't have this issue. Can you precise the version of packages used and python version ?

**Comment by pierrepo** [comment]
Python 3.5.2
weblogolib : 3.5.0
matplotlib 1.5.3
Last version of PBxplore on the master branch

**Comment by HubLot** [comment]
Thanks. The file is empty (size of 0) or unreadable ?

**Comment by pierrepo** [comment]
The file is built, not empty (I believe it's the correct size) but is unreadable.
I tried  all possible formats (png, jpg and pdf). Always unreadable.

**Comment by HubLot** [comment]
Indeed, I have this issue with Python 3 but not Python 2...

**Comment by HubLot** [comment]
It's due to encoding.

**Comment by HubLot** [comment]
close in #153
