### ISSUE TITLE
Update license to BSD?

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/PBxplore#157]
I like this remark taken from [here](https://barbagroup.github.io/essential_skills_RRC/openlicenses/openlicensing/)

> Illustrating how subtle language variations matter, we recently decided to change our pick to the BSD 3-clause License. It is very similar to the MIT License, but there is a small difference in the wording about attribution (which we learned about from a comment by A. Scopatz on a GitHub discussion thread).

> The MIT License says:

>>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

> While BSD 3-clause says:

>> Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

> As Scopatz noted, this language implies that a user could copy some of an MIT-licensed code (as long as the portion is deemed "not substantial") without attribution. In academia, we always prefer full attribution of any portions of copied works, and BSD 3-clause is more precise in this.

I propose we go to BSD license.
What do you think @jbarnoud @HubLot ?

**Comment by HubLot** [comment]
I'm not fully competent to have a critical comparison between MIT and BSD so I let you decide guys :)

**Comment by jbarnoud** [comment]
I have nothing against any of these licenses. The 3-clauses BSD seems slightly less ambiguous, but I doubt the difference actually matters at the scale of the project.
