### ISSUE TITLE
Two tests 'xfailed'

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/PBxplore#167]
By running tests with the last version of PBxplore (after integration of pytest as the new test engine):

    import pbxplore
    pbxplore.test()

I encountered two `xfail` tests:

    pbxplore/tests/test_regression.py::TestPBAssign::test_different_outputs xfail
    pbxplore/tests/test_regression.py::TestPBstat::test_weblogo_logo_invalid_format xfail

These xfailed tests do not seem very problematic since the final return code of the test suite is 0 (i.e. success). @jbarnoud could you have a look?

**Comment by jbarnoud** [comment]
`xfail` means that the test is expected to fail; in this case, they even have to fail (they are set to be strict failures). So everything is perfectly normal here.

**Comment by pierrepo** [comment]
Hence the return code of 0.
Thanks for the explanation @jbarnoud.
