### ISSUE TITLE
Link the paper and explain how to cite

### ISSUE THREAD

**Issue by jbarnoud** [pierrepo/PBxplore#170]
Now that the paper is published, we should tell the world on the README, the doc, and the program.

**Comment by pierrepo** [comment]
OK for the README, the doc, and probably a `CITING.md` in the source repo. Is it OK?

**Comment by jbarnoud** [comment]
I am not sure `CITING.md` is needed, but it cannot hurt.

**Comment by HubLot** [comment]
close in #171
