### ISSUE TITLE
new Weblogo library issue

### ISSUE THREAD

**Issue by alexdb27** [pierrepo/PBxplore#173]
_The Weblogo library had been modified (changed from weblogolib to weblogo). I believe so it must be modified:_ 

_In_
**pbxplore/analysis/visualization.py**

_perhaps in_ 
**pbxplore/scripts/PBstat.py
pbxplore/scripts/test.py
pbxplore/tests/test_regression.py**

_We need to modify_
**import weblogolib**
_by_
**import weblogo as weblogolib**

_And in_ 
**pbxplore/tests/__init__.py**
_Change_ 
**module_info("weblogolib")**
_by_ 
**module_info("weblogo")**

_I think, it is sufficient, but I am not sure ... ??_

**Comment by HubLot** [comment]
fixed in #175
