### ISSUE TITLE
PBclust does not appear in the demo

### ISSUE THREAD

**Issue by jbarnoud** [pierrepo/PBxplore#19]
None of the demos call PBclust.

**Comment by alexdb27** [comment]
If we want to have PBclust, must we keep the demo2 .gro file?

**Comment by jbarnoud** [comment]
On 12/03/15 14:44, Alexandre G. de Brevern wrote:
>
> If we want to have PBclust, must we keep the demo2 .gro file?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pierrepo/PBxplore/issues/19#issuecomment-78481449>.
>
We need to have a set of conformations. It can be either a multimodel  
PDB or a XTC trajectory. It may be long for a demo if there is too many 
conformations. Yet, we may want the conformations not to be too close 
from one another; this means that the file reduction mentioned in #42 
should not be about truncating the file be rather about remove one model 
every X.
