### ISSUE TITLE
PBxplore should be available on Pypi

### ISSUE THREAD

**Issue by jbarnoud** [pierrepo/PBxplore#22]
Pypi (<https://pypi.python.org/pypi>) is the central package repository for the python language. It is where pip and easy_install look for packages to install. Having PBxplore available on pypi would ease the installation of the tools for the users. Getting the software is the first barrier to entry for a user, it should be as smooth as possible.

So far, installing the software means:

* having git installed
* cloning the repo
* changing the PATH to have the executables available anywhere
* changing the PYTHONPATH to have the modules available anywhere
* installing the required python module

This is long and requires some expertise with git and system administration.

Fixing issue #21 would make things slightly easier:

* having git installed
* cloning the repo
* typing `python setup.py install`

In addition to being shorter and to take care automatically of the python module requirements, this procedure is also directly compatible with virtualenv.

Fixing this issue would make the installation process trivial:

* `pip install PBxplore`

Note that fixing issue #21 is a requirement to fix this issue.

**Comment by pierrepo** [comment]
This could help:
http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by alexdb27** [comment]
Coucou,

Dans ce cadre, je dirais que je suis bien entendu 200% d'accord.
Je me permet de partager mes quelques problèmes récents:

-Sous Ubuntu, l'installation de MDAnalysis à nécessité l'utilisation non pas juste du sudo, mais de root (car manquait un package developpement Python) et maintenant je tombe sur https://github.com/pierrepo/PBxplore/issues/26
(mais avec demo2 !! cela fait pas top).

- je teste sous last Mac, ok demo1, par contre j'ai là encore un problème d'install de MDAnalysis (j'ai installé MacPorts, mais il ne trouve pas de repository ...).

Bref un peu complex.

Al+

**Comment by HubLot** [comment]
https://pypi.python.org/pypi/pbxplore
