### ISSUE TITLE
[proposal] PBxplore modularization

### ISSUE THREAD

**Issue by jbarnoud** [pierrepo/PBxplore#25]
The current version of PBxplore is mostly oriented toward a use through the command line. With some refactoring, the program could also be used as a python module which would dramatically increase its extensibility. I hereby propose a structure for PBxplore as a python library in the hope it will lead to a conversation.

PBxplore provides a structure file parser, a Protein Blocks assignment implementation, and some analysis tools. The PB assignment and the analysis can be accessed by the user through command line programs. Yet, they cannot be accessed directly within a python script. A basic use of PBxplore within python would be to get a PB sequence from a protein 3D structure to run custom analyses. To do this with the current version of PBxplore, one needs to run PBassign.py using subprocess and read the fast file that is generated. Such procedure is burdensome; it implies to change context from python to the command line, to create a separate process, and to create a temporary file which should be deleted later. The corresponding code could be:

```python
# Not tested of course, take with caution.
import subprocess
import os
import PBlib
 
# The name of the input file without extension
structure_name = ’test’
# The file name of the temporary fast file
fasta_fname = structure_name + ‘.PB.fasta’
# We call PBassign which generate a fast file
subprocess.call([‘PBassign.py’, ‘-p’, structure_name, ‘-o’, structure_name])
# We read the fast file using a function provided by PBxplore
headers, sequences = PBlib.read_fasta(fasta_fname)
# We delete the temporary fast fila as it is not useful anymore
os.remove(fasta_fname)
# We finally get the PB sequence we wanted
pb_sequence = sequences[0]
```

With the refactoring I propose hereby, obtaining a PB sequence from a PDB file could be coded this way:

```python
import pbxplore
import pbxplore.structure

# The path to the input structure file
structure_fname = ’test.pdb’
# We read a single structure from the PDB file
protein_structure = pbxplore.structure.read_pdb_single(structure_fname)
# We get the PB sequence; as PB assignment only needs dihedral angles,
# the assignment method input is a list of dihedrals
pb_sequence = pbxplore.assign(protein_structure.dihedrals())

# Assigning a PB sequence from a PDB is a frequent need, so we can have
# a shortcut
pb_sequence = pbxplore.assign_from_pdb(structure_fname)
```

The same gain in readability would be obtained for the current analyses. In addition, a workflow that would do several analyses would mutualise steps that would be repeated in the current state of the program.

The post-refactoring exemple also shows the separation of concern and the loose coupling the refactoring would bring. In this proposal, the pbxplore module is divided into four main submodules:
* `pbxplore.assignment` contains the functions directly related to the assignment
* `pbxplore.structure` contains the structure file parsers
* `pbxplore.analysis` contains the analysis functions
* `pbxplore.vizualization` contains functions for data visualisation

Two other submodules are also be included for convenient purpose:
* `pbxplore.data` contains PB related data such as the PB definition and substitution matrices
* `pbxplore.fasta_utils` contains function to read and write fast files

Finally, shortcuts could be access through the pbxplore main module.

A major point of this proposal is the loose coupling between the submodules. The assignment method should not be aware of the structure parser and only asks for a list of dihedral angles. Same wise, the parser is not aware what will be done with the structure but provides, one way or another, a list of dihedral angles. This loose coupling make easier the addition of new parser or the bridges to third party parser. Here are some exemple of data source that could be used by PBxplore users:
* GRO file parser
* interface with the mdtraj library
* output of g_angles
* amber or charmm trajectory parser
* PDB parser aware of protein structure specificities and experimental tricks

The same loose coupling would allow the analysis function to obtain the PB sequences from alternative sources too:
* database of PB sequences
* alternative assignment tool
* alternative structural alphabet
* data altered by other analyses and filters

By outputting the results using the simplest data structures, the module would ease significantly the development of new analyses and visualisation.

The command line tools are an important part of PBxplore and should be maintained and extended. In this model, they are wrapper around the corresponding functions in the library which allows clearer code and better testing.

Here is the suggested architecture of the PBxplore library. The architecture of the command line tools remains unchanged. Note that only the functions of the “public API” are reported bellow. Note also that some functions may be missing, especially in the analysis and visualisation modules.

* `pbxplore.structure`
    * `pbxplore.structure.read_pdb_single`
    * `pbxplore.structure.read_pdb_multi`
    * `pbxplore.structure.read_mmcif_single`
    * `pbxplore.structure.read_mmcif_multi`
    * `pbxplore.structure.read_xtc`
* `pbxplore.assignment`
    * `pbxplore.assignment.assign`
    * `pbxplore.assignment.assign_matrix`
* `pbxplore.analysis`
    * `pbxplore.analysis.count`
    * `pbxplore.analysis.distribution_matrix`
    * `pbxplore.analysis.neq`
    * `pbxplore.analysis.hclust`
* `pbxplore.vizualization`
    * `pbxplore.vizualization.weblogo`
* `pbxplore.data`
    * `pbxplore.data.definition`
    * `pbxplore.data.subtitution`
* `pbxplore.fasta_utils`
    * `pbxplore.fasta_utils.read_fasta`
    * `pbxplore.fasta_utils.write_fasta`
* `pbxplore`
    * `pbxplore.assign` -> `pbxplore.assignment.assign`
    * `pbxplore.assign_matrix` -> `pbxplore.assignment.assign_matrix`
    * `pbxplore.assign_from_pdb`
    * `pbxplore.assign_from_mmcif`
    * `pbxplore.matrix_from_pdb`
    * `pbxplore.matrix_from_mmcif`
    * `pbxplore.matrix_from_xtc`

Alternatively, parts of the code that rely on third party tools such as mdanalysis and weblogo could be separated to ease the gestion of the dependancies.

Here are the tasks related to this proposal:
- [ ] Finish the regression tests for all command line tools. These large changes should not affect how the command line tools works (invocation syntax, so as input and output files should remain unchanged).
- [ ] Make PBxplore installable (see issue #21)
- [ ] Reorganise the code to fit the proposed structure
- [ ] Make sure all functions from the public API are documented
- [ ] Write a narrative documentation

**Comment by pierrepo** [comment]
Agree but I sugget we transform one program after another, starting with PBassign.py

**Comment by jbarnoud** [comment]
I agree it is safer. I'll start by having everything PBassign does available as a library.

**Comment by alexdb27** [comment]
Is everything ok ?
Sincerely

**Comment by jbarnoud** [comment]
On 22/04/15 10:21, Alexandre G. de Brevern wrote:
>
> Is everything ok ?
> Sincerely
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pierrepo/PBxplore/issues/25#issuecomment-95071271>.
>
6 pull requests merged yesterday. We are definitively progressing on the 
matter.

**Comment by pierrepo** [comment]
Yes. @jbarnoud had hard time in both modularizing PBxplore and testing newly created functions. PBcount.py is now modularized.

**Comment by alexdb27** [comment]
cool !!!
