### ISSUE TITLE
Erreur PBassign lors de l'utilisation de fichier gro et xtc

### ISSUE THREAD

**Issue by sleonard0386** [pierrepo/PBxplore#26]
Lors du lancement de la commande PBassign.py avec un fichier xtc et un
fichier gro, j'ai l'erreur suivante :

PBxplore# ./PBassign.py -x test/md.xtc -g test/md.gro -o test/md_traj
/home/alesia/fadeev/Documents/www/PBxplore
Read PB definitions: 16 PBs x 8 angles
Traceback (most recent call last):
  File "./PBassign.py", line 300, in <module>
    atom = PdbAtom()
NameError: name 'PdbAtom' is not defined

En analysant le script PBassign.py, l'occurrence 'PdbAtom' apparaît
uniquement à la ligne 300 et la classe n'est jamais défini. J'ai comparé avec une ancienne version du script fonctionnel ; dans  celle ci, il y a bien la définition d'une
classe 'PdbAtom' en début de script...

-------------
PBxplore-Git# grep -e 'PdbAtom' -r *
PBassign.py:            atom = PdbAtom()

PBxplore-oldversion# grep -e 'PdbAtom' -r *
PBassign.py:class PdbAtom:
PBassign.py:                atom = PdbAtom()
PBassign.py:            atom = PdbAtom()

**Comment by sleonard0386** [comment]
PS : Je suis en train de voir avec Alex pour vous fournir des fichiers gro et xtc utilisable en test & demo

**Comment by sleonard0386** [comment]
[Update] Un test avec les fichier xtc & gro présent dans le dossier demo2 permet de reproduire l'erreur : 

./PBassign.py -x demo2/md_traj_4.xtc -g demo2/md_traj_4.gro  -o test/md_traj
/home/alesia/fadeev/Documents/www/PBxplore
Read PB definitions: 16 PBs x 8 angles 
Traceback (most recent call last):
  File "./PBassign.py", line 300, in <module>
    atom = PdbAtom()        
NameError: name 'PdbAtom' is not defined

**Comment by jbarnoud** [comment]
Last working commit seems to be 10cb0e2.
