### ISSUE TITLE
Problème Weblogo

### ISSUE THREAD

**Issue by sleonard0386** [pierrepo/PBxplore#27]
Hello, c'est encore moi...

Lors de l'utilisation de fichier count de grande taille avec PBstat, l'appel de weblogo renvoie l'erreur suivante : 
ERROR: Traceback (most recent call last):
  File "/usr/local/weblogo/weblogo", line 71, in <module>
    weblogolib._cli.main()
  File "/usr/local/weblogo/weblogolib/_cli.py", line 79, in main
    data = _build_logodata(opts)
  File "/usr/local/weblogo/weblogolib/_cli.py", line 152, in _build_logodata
    options.input_parser.read,
AttributeError: 'str' object has no attribute 'read'

ERROR: exit code != 0
exit code: 1

Je vous mets en PJ un fichier count fonctionnel & un fichier count qui renvoie l'erreur.

D'après les tests que j'ai réalisé avec le stagiaire d'Alex, l'erreur doit venir d'un pb de taille de variable interne à weblogo...

Sylvain

PS: les fichiers ont une extension png pour pouvoir être uploadé ....

 
![md_traj bug count](https://cloud.githubusercontent.com/assets/11348054/6526463/7a94863a-c412-11e4-8fc7-a5d75c247e88.png)
![md_traj fonctionnel count](https://cloud.githubusercontent.com/assets/11348054/6526462/7a9311ba-c412-11e4-8b8e-50ab4067d125.png)

**Comment by jbarnoud** [comment]
Salut @sleonard0386 ,

Merci pour ton rapport de bug.

Quelle version de weblogo utilises-tu ? J'ai essayé avec la version 3.4 (que j'ai installé avec la commande `pip install --user weblogo`), le fichier le plus court a causé un soucis mais le fichier le plus long a marché.

J'ai soumis le pull request #33 qui devrait résoudre le soucis. Ça m'intéresserait que tu essaie chez toi.

**Comment by sleonard0386** [comment]
Hello,

sur la machine, j'utilise la version 3.3 de weblogo que j'ai récupéré sur le site de weblogo : https://code.google.com/p/weblogo/

Je ne sais pas si cela peut venir de là.

Je peux tester de faire l'install de weblogo via pip pour voir si cela supprime le bug. Je peux aussi faire un update de mon git local pour voir si cela fix le bug.

**Comment by jbarnoud** [comment]
J'ai testé la version corrigée avec weblogo 3.4. A priori ça marche. Si c'est possible, je serais surtout intéressé que tu tests la branche corrigée avec ta version actuelle de weblogo. Tu peux trouver la version corrigée de PBxplore appliquant localement le pull request #33 ou en clonant mon dépôt et en faichant un checkout sur la branche issue_weblogo (https://github.com/jbarnoud/PBxplore/tree/issue_weblogo).

Merci d'avoir noté le bug en tout cas.

**Comment by sleonard0386** [comment]
je viens de tester avec ton dépôt & ta branche issue_weblogo, je n'ai plus de problème : 

Index of first residue is: 1
wrote ../test/testG/md_traj_john.PB.map.png

wrote ../test/testG/md_traj_john.PB.Neq
wrote ../test/testG/md_traj_john.PB.Neq.png

wrote ../test/testG/md_traj_john.PB.logo.pdf

Merci pour la résolution du pb

**Comment by jbarnoud** [comment]
On 09/03/15 11:16, sleonard0386 wrote:
>
> je viens de tester avec ton dépôt & ta branche issue_weblogo, je n'ai 
> plus de problème :
>
> Index of first residue is: 1
> wrote ../test/testG/md_traj_john.PB.map.png
>
> wrote ../test/testG/md_traj_john.PB.Neq
> wrote ../test/testG/md_traj_john.PB.Neq.png
>
> wrote ../test/testG/md_traj_john.PB.logo.pdf
>
> Merci pour la résolution du pb
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pierrepo/PBxplore/issues/27#issuecomment-77828511>.
>
Super ! Donc on peut fermer le ticket dès que la pull request est 
reviewée et mergée.

**Comment by sleonard0386** [comment]
Et tu vas rire, pull pas trop vite on a débusqué un nouveau lièvre.....

Le même problème est apparu dans PBassign (après test sur ton dépôt ^^) : 

./PBassign.py -x ../test/testG/md.xtc -g ../test/testG/md.gro -o ../test/testG/md_traj-test
/home/alesia/Documents/www/PBxplore
Read PB definitions: 16 PBs x 8 angles 
Traceback (most recent call last):
  File "./PBassign.py", line 300, in <module>
    atom = PdbAtom()        
NameError: name 'PdbAtom' is not defined

Enjoy....

**Comment by jbarnoud** [comment]
On 09/03/15 13:35, sleonard0386 wrote:
>
> Et tu vas rire, pull pas trop vite on a débusqué un nouveau lièvre.....
>
> Le même problème est apparu dans PBassign (après test sur ton dépôt ^^) :
>
> ./PBassign.py -x ../test/testG/md.xtc -g ../test/testG/md.gro -o 
> ../test/testG/md_traj-test
> /home/alesia/Documents/www/PBxplore
> Read PB definitions: 16 PBs x 8 angles
> Traceback (most recent call last):
> File "./PBassign.py", line 300, in
> atom = PdbAtom()
>
> NameError: name 'PdbAtom' is not defined
>
> Enjoy....
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pierrepo/PBxplore/issues/27#issuecomment-77845286>.
>
Ce n'est pas un nouveau bug, c'est le bug #26 qui n'est pas corrigé sur 
cette branche. Je fais une branche par correction de bug pour que les 
pull requests soient le plus spécifique possible.

En attendant que les pull requests soient validées par Pierre, tu peux 
localement merger les branches qui corrigent tes soucis. Pour le soucis 
que tu décris ici, tu peux regarder la branche pull_xtc de mon dépôt.

**Comment by sleonard0386** [comment]
Oui, désolé pour le commentaire ici, je me suis rendu compte 10s après l'avoir posté que je m'étais planté....
(d'où la suppression du post)
