### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by alexdb27** [pierrepo/PBxplore#30]
Coucou,

Bon quelques pépins spécifiques de test sous Mac.

- ok, un peu **** l'installation des qq packages, mais bon (ok, pas réussi pour MDAnalysis ar macports ne marche pas).
- weblogo ne passe pas en ligne de commande. Il dit qu'il ne trouve pas dans le sh alors que j'ai mis dans le même répertoire avec tout ce qu'il faut (bestial), weblogo fonctionne (sa démo)... je creuserais.

**Comment by jbarnoud** [comment]
We should document how to install the dependancies. I will do it once the install protocol for PBxplore is stabilized (see #21 and #22).

Hint: one should use pip to install the dependancies:

```
pip install mdanalysis weblogo  # system wide install
pip install --user mdanalysis weblogo  # local install for the current user
```

Even better, look at virtualenv.

**Comment by alexdb27** [comment]
pip pour Linux
cela marche pour weblogo ??

sous mac, j'ai du passé par MacPorts, un peu long (5 heures) et pleins de problèmes ... mais bon cela marche maintenant ...(enfin j'arrive au même bug que sous Linux)

On a une idée de test sous Windows ou il faut un truc style Cygwin ?

**Comment by jbarnoud** [comment]
A priori il n'y a pas de soucis à installer weblogo avec pip sous linux, mais je n'ai rien pour tester sous la main. Il faut être root pour l'installer au niveau du système mais l'option --user de pip permet d'installer des paquets sans droit particulier.

Je ne sais pas comment utiliser le PBxplore sous windows. Ça devrait être possible de l'utiliser depuis la commande DOS sans utiliser cygwin. Mais je ne connais pas assez windows pour te dire comment faire.

**Comment by alexdb27** [comment]
So test ok for mac OSX Yosemite 10.10.1, Python 2.7.6, R 3.1.1. weblogo 3.3 
(exactly same results than for Linux)

**Comment by alexdb27** [comment]
I've seen on http://deeplearning.net/software/theano/install.html#install ... about Enthought Python Distribution (EPD)

MacOS
There are various ways to install Theano dependencies on a Mac. Here we describe the process in detail with EPD, Anaconda or with MacPorts, but if you did it differently and it worked, please let us know the details on the theano-users mailing-list, so that we can add alternate instructions here.

In academia: Enthought Python Distribution (EPD)
If you are working in academia, the easiest way to install most of the dependencies is to install Enthought Python Distribution (EPD). If you are affiliated with a university (as student or employee), you can download the installer for free.

EPD installation includes in particular Python (and the development headers), NumPy, SciPy, nose, sphinx, easy_install, pydot (but not Graphviz, which is necessary for it to work) and the MKL implementation of blas. The Mac OS and Linux version do not include g++.

**Comment by jbarnoud** [comment]
I split this issue in #101 and #102 to have only one issue per topic.
