### ISSUE TITLE
clusters

### ISSUE THREAD

**Issue by alexdb27** [pierrepo/PBxplore#31]
1. il faudrait expliciter la méthodologie.
2. le premier exemple ne donne pas le même résultat !!!
j'ai 28 - 17 - 26 - 53 - 66 séquences au lieu de 9 - 16 -48 -52 - 65 !!!
(le nom n'zst aps md_traj_1.PB.clust mais beta_....)

3. --cluster options ? cluster !
idem pas la même chose...

**Comment by jbarnoud** [comment]
La doc de PBclust n'a pas l'air à jour et la copie de la sortie de PBclust ne correspond pas à la sortie que l'on obtient en lançant l'exemple. J'ai la même sortie qu'Alex en lançant l'exemple.

Après un rapide coup d'oeil, je pense que la différence vient de la méthode de clustering passée à hclust qui est passée à ward dans le commit 6f75a9a1a9824fa40454911e166c9c65b4736d63.

Il faudrait mettre la doc à jour mais il faudrait aussi se poser la question de si la méthode ward est vraiment celle que l'on souhaite utiliser. Sur ce dernier point (que m'a pointé Alex la denière fois qu'on s'est vu), voir <http://stats.stackexchange.com/questions/109949/what-algorithm-does-ward-d-in-hclust-implement-if-it-is-not-wards-criteria>.

@alexdb27 Je ne comprends pas ton point 3. Quel est le problème ?

cc @pierrepo

**Comment by alexdb27** [comment]
Pour le ward, il y eu en effet une mise à jour.
Deux types de calcul existe, l'un correct, l'autre plus approximatif. 
C'était le second qui était dans R, ils ont corrigé et propose les deux.
mon opinion est de mettre le "bon" ward et si possible un complete si l'utilisateur le désire

Point 3, il y a des fötes de tograffe ... zats all !!

**Comment by pierrepo** [comment]
So which clustering method should I use @alexdb27 ? Ward or Complete ?
I am sure proposing an option for either ward or complete will be usefull.

**Comment by alexdb27** [comment]
YES !! Excellent idea(s) :+1:  I agree @ 200%

**Comment by pierrepo** [comment]
Actually a word was missing
> I am **not** sure proposing an option for either ward or complete will be usefull.
Couldn't we stick to one method?

**Comment by alexdb27** [comment]
I would say Ward by default and optionnaly complete
It is very difficult to choose without testing on a series of simulations.
Mathhieu can test if you need.

**Comment by pierrepo** [comment]
Yes, please. I am bit reluctant to add a new option. But I'll do if we need to.

**Comment by pierrepo** [comment]
Obviously, we have problems with R clustering:
- method names changed
- bugs with many conformations as reported by @alexdb27 and Sylvain

Worth looking at alternatives ? Pycluster ? Scikit-learn ?

**Comment by jbarnoud** [comment]
Hierarchical clustering is implemented in [scipy](http://docs.scipy.org/doc/scipy/reference/cluster.hierarchy.html) and other libraries (<http://nbviewer.ipython.org/github/OxanaSachenkova/hclust-python/blob/master/hclust.ipynb>, <http://bioinformatics.org.au/tools/hclust/>), including [scikit-learn](<http://scikit-learn.org/stable/modules/generated/sklearn.cluster.AgglomerativeClustering.html#sklearn.cluster.AgglomerativeClustering>). I do not know Pycluster.

See also #13 about getting rid of R completely.

**Comment by jbarnoud** [comment]
We will fix this issue by using k-means rather than hclust. See #64. I close the issue.
