### ISSUE TITLE
Probleme with run_demo1.sh

### ISSUE THREAD

**Issue by sleonard0386** [pierrepo/PBxplore#37]
Un petit retour de bug de l'étudiant d'Alex sur ce script : 

Certaine commande echo ne corresponde pas à la commande lancée réellement
exemple : 
echo "../PBassign.py -f 2LFU.pdb -o 2LFU"
puis
../PBassign.py -p 2LFU.pdb -o 2LFU

ou encore

echo "../PBassign.py -d ./ -o all"
puis
../PBassign.py -p 3ICH.pdb -p 2LFU.pdb -o several

Enfin, pour la commande permettant de lire un dossier, le retour d'echo n'est pas identique à la commande lancée & la commande lancée renvoie en console 'Nothing to do' : 
affichage de commande : echo "../PBassign.py -d ./ -o all"
&
lancement de : ../PBassign.py -p ./ -o all

Voili

PS : comment faire pour lancer la commande sur tous les fichiers d'un dossier sans faire une multitude de -p ou un script externe ?

**Comment by Vivi270** [comment]
ou encore

echo "../PBassign.py -d ./ -o all"
puis
../PBassign.py -p 3ICH.pdb -p 2LFU.pdb -o several

Enfin, pour la commande permettant de lire un dossier, le retour d'echo n'est pas identique à la commande lancée & la commande lancée renvoie en console 'Nothing to do' : 
affichage de commande : echo "../PBassign.py -d ./ -o all"

**Comment by jbarnoud** [comment]
A priori ça vient d'être résolu :)
