### ISSUE TITLE
Reduce file redundancy in demo and test directories

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/PBxplore#41]
Some structures files in the test_data directory are redundant with some from the demo1 or demo2 directory. Could we reduce this redundancy by taking source structures files for test in the demoX directory?
Symlinks are not good idear since probably not cross plateform.
If needed, we can merge demo1 and demo2 directories into a single demo dir.

**Comment by jbarnoud** [comment]
It could be done. Yet, I would prefer the tests to remain as independent from the rest as possible.

**Comment by pierrepo** [comment]
OK. For me. Maybe I'll try to reduce the size of some test files....

**Comment by jbarnoud** [comment]
On 10/03/15 14:58, Pierre Poulain wrote:
>
> OK. For me. Maybe I'll try to reduce the size of some test files....
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pierrepo/PBxplore/issues/41#issuecomment-78057746>.
>
The PDBs with multiple models and the trajectories are easy target here. 
demo2/md_traj.pdb especially makes the demo super slow and quite painful 
to run.
