### ISSUE TITLE
PBclust should not have a default number of clusters 

### ISSUE THREAD

**Issue by jbarnoud** [pierrepo/PBxplore#45]
This may be controversial, but I do not think PBclust should have a default number of clusters. While I understand that it is convenient for beginners to have a minimum of options to care about, I think the number of clusters should be chosen based on the user knowledge of the system and the problem. Having a default value for the number of clusters hides the importance of this choice. 

In addition, a default value should make sense in most cases. Yet, in most cases, 5 is not a pertinent number of clusters. 

Therefore, I think the clusters argument of PBclust should be mandatory, and should not have a default value.

**Comment by pierrepo** [comment]
I agree.

**Comment by alexdb27** [comment]
I agree with the PBxplore's gods.
Default is good.

**Comment by alexdb27** [comment]
As it had been tested ?
