### ISSUE TITLE
Improve defintion of color scheme in PB maps

### ISSUE THREAD

**Issue by pierrepo** [pierrepo/PBxplore#52]
So far, definition of color scheme is defined in PBstats.py:

    grad = matrix(nrow=848, ncol=3)
    grad[1,1] = 20
    grad[1,2] = 20
    grad[1,3] = 232
    for(i in 2:212){
    grad[i,1] = grad[i-1,1]
    grad[i,2] = grad[i-1,2]+1
    grad[i,3] = grad[i-1,3]
    }
    for(i in 213:424){
    grad[i,1] = grad[i-1,1]
    grad[i,2] = grad[i-1,2]
    grad[i,3] = grad[i-1,3]-1
    }
    for(i in 425:636){
    grad[i,1] = grad[i-1,1]+1
    grad[i,2] = grad[i-1,2]
    grad[i,3] = grad[i-1,3]
    }
    for(i in 637:848){
    grad[i,1] = grad[i-1,1]
    grad[i,2] = grad[i-1,2]-1
    grad[i,3] = grad[i-1,3]
    }
    colorpal = rgb(grad[,1]/255,grad[,2]/255,grad[,3]/255)

R has buit-in color schemes.

**Comment by jbarnoud** [comment]
If we get rid of R (#13), then the definition should be in python :wink:

**Comment by alexdb27** [comment]
Is it needed now (or later) ?

**Comment by alexdb27** [comment]
had it been done ?

**Comment by pierrepo** [comment]
I am currently dealing with this issue. Here are the requirements for the improved color scheme : 
- sequential, since we want to pinpoint PBs with highest frequencies
- colorblind-friendly

**Comment by pierrepo** [comment]
Color scheme for PB frequencies map has been taken from ColorBrewer : 
http://colorbrewer2.org/?type=diverging&scheme=RdYlBu&n=5

- diverging color scheme for a better contract between PB with high frequencies and PBs with low frequencies.
- colorblind safe

Now in the get_rid_of_R branch.

**Comment by alexdb27** [comment]
Do you have enough variations for the colors?

**Comment by pierrepo** [comment]
Yes, it should.
I transformed the discrete color scheme taken from [ColorBrewer](http://colorbrewer2.org/?type=diverging&scheme=RdYlBu&n=5) to a continuous colormap.
