### ISSUE TITLE
Weblogos are only available in PDF format

### ISSUE THREAD

**Issue by jbarnoud** [pierrepo/PBxplore#73]
PBstat only produce weblogo in PDF format while the weblogo program can produce a large variety of formats. A `--logo-format` option would allow to choose the file format to produce.

While PDF is the best format for logos in most case, it is difficult to embed in other documents (including ipython notbooks).

**Comment by HubLot** [comment]
+1 !

**Comment by pierrepo** [comment]
I would like to minimize the number of possible options in PBxplore.
Adding an option to choose a logo format implies the implementation of tests that the format provided is correct. We did not implement such a thing for Neq and PBs map (matplotlib can generate many ouput formats too).
I suggest we produce WebLogo in png format with a good resolution, as we do for Neq and PBs map. This will certainly covers 99% of user cases.

**Comment by jbarnoud** [comment]
On 17/09/15 16:38, Pierre Poulain wrote:
>
> I would like to minimize the number of possible options in PBxplore.
> Adding an option to choose a logo format implies the implementation of 
> tests that the format provided is correct. We did not implement such a 
> thing for Neq and PBs map (matplotlib can generate many ouput formats 
> too).
> I suggest we produce WebLogo in png format with a good resolution, as 
> we do for Neq and PBs map. This will certainly covers 99% of user cases.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pierrepo/PBxplore/issues/73#issuecomment-141106891>.
>
Testing that the format is correct is built into argparse. In the PR, 
the test for the format is there; it is right in the definition of the 
--logo-format option.

I did not think about the other outputs. I think it is good to be able 
to choose the file format of the pictures. PNG is the most useful while 
we do explore, yet a lot of journals ask for EPS or PDF images. Also, 
vector graphics are better in a lot of situations. What we could have is 
a --image-format option that would control the output format of all the 
images. Then, the neq, the PB map, and the logos can be obtained in a 
large variety of formats with a single option added.

**Comment by pierrepo** [comment]
Grrr.
OK for an --image-format option. But : 
- only .pdf, .png and .jpg. 
- eps can be obtained from pdf (and we are not in the XXe century anymore).
- png is the default format.

All good?

**Comment by jbarnoud** [comment]
Done. See #74
