### ISSUE TITLE
pbxplore.assign is overwritten

### ISSUE THREAD

**Issue by jbarnoud** [pierrepo/PBxplore#83]
Following #80, the function `pbxplore.assign` overwrite the module `pbxplore.assign` in `pbxplore.__init__.py`. A solution would be to rename the module `assignment`.

cc @HubLot

**Comment by HubLot** [comment]
Indeed, I did not realize this bug when doing the modularization.
I will submit a PR

**Comment by HubLot** [comment]
Fix in #84
