### ISSUE TITLE
Set Readthedocs

### ISSUE THREAD

**Issue by jbarnoud** [pierrepo/PBxplore#90]
See pull request message in #82.

Can only be done by @pierrepo .

**Comment by pierrepo** [comment]
I have an error with RTD:
https://readthedocs.org/projects/pbxplore/builds/3395010/

It seems numpy is not installed with MDAnalysis?

**Comment by jbarnoud** [comment]
Did you set the install of the requirements from `doc_requirements.txt`?

**Comment by jbarnoud** [comment]
@pierrepo  look at the pull request description in #82 for all the options to set

**Comment by pierrepo** [comment]
@jbarnoud No!
Now yes, but:
https://readthedocs.org/projects/pbxplore/builds/3396374/

**Comment by jbarnoud** [comment]
* requirements must be installed from `doc_requirements.txt`
* the system sipe-package must be accessible
* PDF doc must be deactivated

**Comment by pierrepo** [comment]
http://pbxplore.readthedocs.org/en/latest/ ;-) Thanks @jbarnoud 

I found the doc process a bit complicated. I that normal?

**Comment by jbarnoud** [comment]
There were 3 important points to setup. But they were to setup only once. Now the doc should build automatically at each commit.
