### ISSUE TITLE
folder demo_paper 

### ISSUE THREAD

**Issue by HubLot** [pierrepo/PBxplore#95]
Is this folder still needed/used ? I don't see where in the files.
If not, it can be removed.

**Comment by pierrepo** [comment]
This folder is /was a case study to explain PBxplore functionalities in the research paper we are going to publish. 

I have to update it with all the modifications we made. 


Le 16 octobre 2015 10:03:05 GMT+01:00, Hub <notifications@github.com> a écrit :
>Is this folder still needed/used ? I don't see where in the files.
>If not, it can be removed.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pierrepo/PBxplore/issues/95

-- 
Pierre Poulain
http://cupnet.net

**Comment by HubLot** [comment]
Okay. I was cleaning the depot for the packaging and I was wondering.

**Comment by pierrepo** [comment]
However, the demo_paper folder should be outside the package.

**Comment by jbarnoud** [comment]
The question is answered so I close the issue.
